// `_redirects` and `_headers` for Netlify, generated after the build, plus a small reader for both
// formats so the local test server (e2e, Lighthouse) behaves like the real host.
import { createHash } from 'node:crypto';

/** First match wins. Real files take precedence over rewrites on Netlify, as on the test server. */
export function buildRedirects({ apiOrigin }) {
  const api = apiOrigin.replace(/\/$/, '');
  return [
    '# Generated by scripts/generate-netlify-files.mjs',
    '# The browser only talks to this site: /api is forwarded to the API host.',
    `/api/*  ${api}/api/:splat  200`,
    '',
    '# The back-office is rendered in the browser only.',
    '/admin  /index.csr.html  200',
    '/admin/*  /index.csr.html  200',
    '',
    '# Send visitors to their language (the browser language, English by default).',
    '/  /ar  302  Language=ar',
    '/  /fr  302  Language=fr',
    '/  /en  302',
    '',
    '# Anything else: the app shows its localized "not found" page with a real 404 status.',
    '/*  /index.csr.html  404',
    '',
  ].join('\n');
}

/** Base64 SHA-256 CSP source of every inline (executable) script in an HTML document. */
export function inlineScriptHashes(html) {
  const hashes = new Set();
  for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    const [, attributes, body] = match;
    if (/\bsrc\s*=/i.test(attributes)) continue;
    const type = /\btype\s*=\s*["']?([^"'\s>]+)/i.exec(attributes)?.[1]?.toLowerCase();
    if (type && !['module', 'text/javascript', 'application/javascript'].includes(type)) continue; // data blocks
    if (!body.trim()) continue;
    hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
  }
  return [...hashes];
}

export function buildCsp({ scriptHashes = [] } = {}) {
  return [
    "default-src 'self'",
    ['script-src', "'self'", ...scriptHashes].join(' '),
    // Component styles and per-element custom properties are applied inline.
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
  ].join('; ');
}

const IMMUTABLE = 'public, max-age=31536000, immutable';

export function buildHeaders({ scriptHashes = [] } = {}) {
  const blocks = [
    [
      '/*',
      {
        'Strict-Transport-Security': 'max-age=63072000; includeSubDomains',
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'DENY',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Permissions-Policy':
          'camera=(), microphone=(), geolocation=(), payment=(), interest-cohort=()',
        'Cross-Origin-Opener-Policy': 'same-origin',
        'Content-Security-Policy': buildCsp({ scriptHashes }),
      },
    ],
    ['/*.html', { 'Cache-Control': 'public, max-age=0, must-revalidate' }],
    ['/*.js', { 'Cache-Control': IMMUTABLE }],
    ['/*.css', { 'Cache-Control': IMMUTABLE }],
    ['/media/*', { 'Cache-Control': IMMUTABLE }],
    ['/content-snapshot.json', { 'Cache-Control': 'public, max-age=0, must-revalidate' }],
    // `/admin/*` does not match `/admin` itself. The browser-only shell serves the back-office and
    // the 404 page, and neither belongs in a search index, so it is covered by its own path too.
    ['/admin', { 'X-Robots-Tag': 'noindex, nofollow', 'Cache-Control': 'no-store' }],
    ['/admin/*', { 'X-Robots-Tag': 'noindex, nofollow', 'Cache-Control': 'no-store' }],
    ['/index.csr.html', { 'X-Robots-Tag': 'noindex, nofollow', 'Cache-Control': 'no-store' }],
  ];
  return [
    '# Generated by scripts/generate-netlify-files.mjs',
    ...blocks.flatMap(([pattern, headers]) => [
      pattern,
      ...Object.entries(headers).map(([name, value]) => `  ${name}: ${value}`),
      '',
    ]),
  ].join('\n');
}

// ---- readers (used by the local test server) ---------------------------------------------------

const lines = (text) =>
  text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'));

export function parseRedirects(text) {
  return lines(text).map((line) => {
    const [from, to, third, ...rest] = line.split(/\s+/);
    const hasStatus = /^\d{3}!?$/.test(third ?? '');
    const status = hasStatus ? Number.parseInt(third, 10) : 301;
    const conditions = Object.fromEntries(
      (hasStatus ? rest : [third, ...rest])
        .filter(Boolean)
        .map((part) => part.split('='))
        .map(([k, v]) => [k.toLowerCase(), v.split(',')]),
    );
    return { from, to, status, conditions };
  });
}

export function parseHeaders(text) {
  const blocks = [];
  for (const raw of text.split('\n')) {
    if (!raw.trim() || raw.trim().startsWith('#')) continue;
    if (/^\s/.test(raw)) {
      const index = raw.indexOf(':');
      blocks.at(-1)?.headers.push([raw.slice(0, index).trim(), raw.slice(index + 1).trim()]);
    } else {
      blocks.push({ pattern: raw.trim(), headers: [] });
    }
  }
  return blocks;
}

const escapeRegex = (value) => value.replace(/[.+?^${}()|[\]\\]/g, '\\$&');

/** Netlify path patterns: `*` matches anything (including `/`), `:name` one segment. */
export function matchPattern(pattern, path) {
  const source = escapeRegex(pattern)
    .replace(/\*/g, '(.*)')
    .replace(/:([a-z]+)/gi, '([^/]+)');
  const match = new RegExp(`^${source}$`).exec(path);
  return match ? { splat: pattern.includes('*') ? (match[1] ?? '') : '' } : null;
}

export function resolveRedirect(rules, path, { acceptLanguage = '' } = {}) {
  const languages = acceptLanguage
    .split(',')
    .map((part) => part.trim().split(/[-;]/)[0]?.toLowerCase())
    .filter(Boolean);
  for (const rule of rules) {
    const hit = matchPattern(rule.from, path);
    if (!hit) continue;
    const wanted = rule.conditions.language;
    if (wanted && !wanted.some((code) => languages[0] === code.toLowerCase())) continue;
    return { to: rule.to.replace(':splat', hit.splat), status: rule.status };
  }
  return null;
}

export function headersFor(blocks, path) {
  const headers = {};
  for (const block of blocks) {
    if (matchPattern(block.pattern, path))
      for (const [name, value] of block.headers) headers[name] = value;
  }
  return headers;
}
